In [8]:
# ===== Cell 1: Imports + Load =====
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("combined_data_clean.csv")
df.columns = df.columns.str.strip()

print("Columns:", df.columns.tolist())
print("Shape:", df.shape)


Columns: ['FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HST', 'AST', 'B365H', 'B365A', 'BWH', 'BWA', 'PSH', 'PSA', 'WHH', 'WHA', 'MaxH', 'MaxA', 'AvgH', 'AvgA', 'AHh', 'B365CH', 'B365CA', 'BWCH', 'PSCH', 'PSCA', 'WHCH', 'MaxCH', 'MaxCA', 'AvgCH', 'AvgCA', 'AHCh', 'IWH', 'IWA', 'VCH', 'VCA']
Shape: (3863, 35)


In [9]:

target = "FTR"

features = [c for c in df.columns if c != target]


leak_cols = ["FTHG", "FTAG"]
features = [c for c in features if c not in leak_cols]

df2 = df.dropna(subset=features + [target]).copy()
X = df2[features]
y = df2[target]

print("Using features:", features)
print("y distribution:\n", y.value_counts())
print("Clean shape:", df2.shape)


Using features: ['HTHG', 'HTAG', 'HST', 'AST', 'B365H', 'B365A', 'BWH', 'BWA', 'PSH', 'PSA', 'WHH', 'WHA', 'MaxH', 'MaxA', 'AvgH', 'AvgA', 'AHh', 'B365CH', 'B365CA', 'BWCH', 'PSCH', 'PSCA', 'WHCH', 'MaxCH', 'MaxCA', 'AvgCH', 'AvgCA', 'AHCh', 'IWH', 'IWA', 'VCH', 'VCA']
y distribution:
 FTR
2    1736
0    1105
1    1022
Name: count, dtype: int64
Clean shape: (3863, 35)


In [ ]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

dt_model = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("dt", DecisionTreeClassifier(
        random_state=42,
        criterion="gini",      
        max_depth=12,
        min_samples_split=4,
        min_samples_leaf=2,
        class_weight="balanced"
    ))
])

dt_model.fit(X_train, y_train)
pred = dt_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))


Accuracy: 0.5523932729624839


In [ ]:

labels = np.unique(np.concatenate([y_test.to_numpy(), pred]))

print("Labels in test/pred:", labels)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred, labels=labels))
print("\nReport:\n", classification_report(y_test, pred, labels=labels, digits=4))


Labels in test/pred: [0 1 2]

Confusion Matrix:
 [[135  63  23]
 [ 54  90  61]
 [ 27 118 202]]

Report:
               precision    recall  f1-score   support

           0     0.6250    0.6109    0.6178       221
           1     0.3321    0.4390    0.3782       205
           2     0.7063    0.5821    0.6382       347

    accuracy                         0.5524       773
   macro avg     0.5545    0.5440    0.5447       773
weighted avg     0.5838    0.5524    0.5634       773



In [ ]:
# ===== Cell 4: Confusion Matrix + Report =====
labels = np.unique(np.concatenate([y_test.to_numpy(), pred]))

print("Labels in test/pred:", labels)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, pred, labels=labels))
print("\nReport:\n", classification_report(y_test, pred, labels=labels, digits=4))


Labels in test/pred: [0 1 2]

Confusion Matrix:
 [[132  79  10]
 [ 59 105  41]
 [ 38 121 188]]

Report:
               precision    recall  f1-score   support

           0     0.5764    0.5973    0.5867       221
           1     0.3443    0.5122    0.4118       205
           2     0.7866    0.5418    0.6416       347

    accuracy                         0.5498       773
   macro avg     0.5691    0.5504    0.5467       773
weighted avg     0.6092    0.5498    0.5650       773

