In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [3]:
df = pd.read_csv("combined_data_clean.csv")
df.head()


,FTHG,FTAG,FTR,HTHG,HTAG,HST,AST,B365H,B365A,BWH,...,WHCH,MaxCH,MaxCA,AvgCH,AvgCA,AHCh,IWH,IWA,VCH,VCA
0,-0.381231,-0.121387,1,0.410169,-0.691476,-0.260731,-0.764263,-0.632409,0.790150,-0.682781,...,-0.729312,-0.742045,0.958909,-0.755015,1.115374,-1.219140,-0.238407,-0.27108,-0.258239,-0.267293
1,-0.381231,-0.121387,1,0.410169,-0.691476,-0.260731,-0.764263,-0.181811,-0.420159,-0.143598,...,-0.051159,-0.119511,-0.416052,-0.126615,-0.399860,0.062436,-0.238407,-0.27108,-0.258239,-0.267293
2,0.399242,-0.121387,2,-0.787181,0.715283,-0.260731,-0.764263,-0.363086,-0.153891,-0.340175,...,-0.347851,-0.369956,-0.117983,-0.333325,-0.101524,0.062436,-0.238407,-0.27108,-0.258239,-0.267293
3,0.399242,0.780346,1,0.410169,0.715283,0.139446,0.629421,0.051256,-0.509722,0.109144,...,0.203148,0.080845,-0.499382,0.129706,-0.505848,0.489628,-0.238407,-0.27108,-0.258239,-0.267293
4,-0.381231,-0.121387,1,-0.787181,0.715283,0.139446,0.164860,-0.440775,-0.057066,-0.469354,...,-0.517389,-0.541689,0.260211,-0.523499,0.314577,-0.364756,-0.238407,-0.27108,-0.258239,-0.267293


In [4]:
y = df["FTR"]   # Full Time Result


In [5]:
features = ["HTHG", "HTAG"]   # Half Time Home Goals, Away Goals
X = df[features].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)


X shape: (3863, 2)
y shape: (3863,)


In [6]:
le = LabelEncoder()
y_enc = le.fit_transform(y)

print("Classes mapping:", list(le.classes_))


Classes mapping: [np.int64(0), np.int64(1), np.int64(2)]


In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_enc,
    test_size=0.2,
    random_state=42,
    stratify=y_enc
)


In [8]:
model = LogisticRegression(
    max_iter=2000
)

model.fit(X_train, y_train)

print("Logistic Regression Trained ✅")


Logistic Regression Trained ✅


In [9]:
y_pred = model.predict(X_test)


In [10]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 0.5782664941785253

Confusion Matrix:
[[117   0 104]
 [ 41   0 164]
 [ 17   0 330]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.53      0.59       221
           1       0.00      0.00      0.00       205
           2       0.55      0.95      0.70       347

    accuracy                           0.58       773
   macro avg       0.41      0.49      0.43       773
weighted avg       0.44      0.58      0.48       773



/Users/ganna/Documents/machine-intelligence-project/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ganna/Documents/machine-intelligence-project/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ganna/Documents/machine-intelligence-project/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter

In [11]:
model_balanced = LogisticRegression(
    max_iter=2000,
    class_weight="balanced"
)

model_balanced.fit(X_train, y_train)

y_pred_bal = model_balanced.predict(X_test)

print("\nBalanced Accuracy:", accuracy_score(y_test, y_pred_bal))

print("\nBalanced Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_bal))

print("\nBalanced Classification Report:")
print(classification_report(y_test, y_pred_bal))



Balanced Accuracy: 0.5666235446313066

Balanced Confusion Matrix:
[[117  89  15]
 [ 41 121  43]
 [ 17 130 200]]

Balanced Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.53      0.59       221
           1       0.36      0.59      0.44       205
           2       0.78      0.58      0.66       347

    accuracy                           0.57       773
   macro avg       0.60      0.57      0.57       773
weighted avg       0.63      0.57      0.58       773

